[package]
name = "strk_payment_handler"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.11.4"

[dev-dependencies]
snforge_std = "0.33.0"

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"